### ISSUE TITLE
Timestamps are not indicated in the spec

### ISSUE THREAD

**Issue by jleclanche** [stripe/openapi#30]
Example:

```yml
        webhooks_delivered_at:
          description: The time at which webhooks for this invoice were successfully
            delivered (if the invoice had no webhooks to deliver, this will match
            `date`). Invoice payment is delayed until webhooks are delivered, or until
            all webhook delivery attempts have been exhausted.
          nullable: true
          type: integer
```

This has type:integer, but the docs show it as type: timestamp.
