### ISSUE TITLE
subscription_item.subscription is nullable

### ISSUE THREAD

**Issue by jleclanche** [stripe/openapi#35]
According to the spec:

```yml
        subscription:
          description: The `subscription` this `subscription_item` belongs to.
          maxLength: 5000
          nullable: true
          type: string
```

How does the nullable make sense here?
