### ISSUE TITLE
subscription_proration_date nullability

### ISSUE THREAD

**Issue by jleclanche** [stripe/openapi#38]
```yml
        subscription_proration_date:
          description: Only set for upcoming invoices that preview prorations. The
            time used to calculate prorations.
          type: integer
```

So I don't understand that field and it's inconsistent with the rest of the API. It's not marked as nullable, but it's marked as *optional*. It sounds like it won't ever show up as `null` but it will simply not show up.

Is that correct? Isn't it simpler to just call it nullable?
